# Tree-Based Algorithms

In [114]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/apartments_0K.csv',low_memory=False)

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             99492 non-null  int64
 1   category       99492 non-null  str
 2   title          99492 non-null  str
 3   body           99492 non-null  str
 4   amenities      83448 non-null  str
 5   bathrooms      99429 non-null  float64
 6   bedrooms       99368 non-null  float64
 7   currency       99492 non-null  str
 8   fee            99492 non-null  str
 9   has_photo      99492 non-null  str
 10  pets_allowed   39068 non-null  str
 11  price          99491 non-null  float64
 12  price_display  99491 non-null  str
 13  price_type     99492 non-null  str
 14  square_feet    99492 non-null  int64
 15  address        7943 non-null   str
 16  cityname       99190 non-null  str
 17  state          99190 non-null  str
 18  latitude       99467 non-null  float64
 19  longitude      99467 non-null  float64
 20  source         99492 non-null  str
 21  time           99492 non-null  int64
dtypes: float64(5), int64(3), str(14)
memory usage: 16.7 MB

In [116]:
df.head()

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668640009,housing/rent/apartment,One BR 507 & 509 Esplanade,"This unit is located at 507 & 509 Esplanade, R...",NaN,1.0,1.0,USD,No,Thumbnail,...,"$2,195.00",Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1577360355
1,5668639818,housing/rent/apartment,Three BR 146 Lochview Drive,"This unit is located at 146 Lochview Drive, Ne...",NaN,1.5,3.0,USD,No,Thumbnail,...,"$1,250.00",Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1577360340
2,5668639686,housing/rent/apartment,Three BR 3101 Morningside Drive,This unit is located at 3101 Morningside Drive...,NaN,2.0,3.0,USD,No,Thumbnail,...,"$1,395.00",Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1577360332
3,5668639659,housing/rent/apartment,Two BR 209 Aegean Way,"This unit is located at 209 Aegean Way, Vacavi...",NaN,1.0,2.0,USD,No,Thumbnail,...,"$1,600.00",Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1577360330
4,5668639374,housing/rent/apartment,One BR 4805 Marquette NE,"This unit is located at 4805 Marquette NE, Alb...",NaN,1.0,1.0,USD,No,Thumbnail,...,$975.00,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1577360308

# Data preprocessing

In [117]:

df.isnull().sum()

id                   0
category             0
title                0
body                 0
amenities        16044
bathrooms           63
bedrooms           124
currency             0
fee                  0
has_photo            0
pets_allowed     60424
price                1
price_display        1
price_type           0
square_feet          0
address          91549
cityname           302
state              302
latitude            25
longitude           25
source               0
time                 0
dtype: int64

In [118]:
df.columns

Index(['id', 'category', 'title', 'body', 'amenities', 'bathrooms', 'bedrooms',
       'currency', 'fee', 'has_photo', 'pets_allowed', 'price',
       'price_display', 'price_type', 'square_feet', 'address', 'cityname',
       'state', 'latitude', 'longitude', 'source', 'time'],
      dtype='str')

In [119]:
df.drop(['amenities','pets_allowed','address','price_display'],axis=1,inplace=True)

In [120]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
    return (df)

In [121]:
df=toldir(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           99492 non-null  int64
 1   category     99492 non-null  str
 2   title        99492 non-null  str
 3   body         99492 non-null  str
 4   bathrooms    99492 non-null  float64
 5   bedrooms     99492 non-null  float64
 6   currency     99492 non-null  str
 7   fee          99492 non-null  str
 8   has_photo    99492 non-null  str
 9   price        99492 non-null  float64
 10  price_type   99492 non-null  str
 11  square_feet  99492 non-null  int64
 12  cityname     99492 non-null  str
 13  state        99492 non-null  str
 14  latitude     99492 non-null  float64
 15  longitude    99492 non-null  float64
 16  source       99492 non-null  str
 17  time         99492 non-null  int64
dtypes: float64(5), int64(3), str(10)
memory usage: 13.7 MB

In [122]:
df.isnull().sum()

id             0
category       0
title          0
body           0
bathrooms      0
bedrooms       0
currency       0
fee            0
has_photo      0
price          0
price_type     0
square_feet    0
cityname       0
state          0
latitude       0
longitude      0
source         0
time           0
dtype: int64

# Encoding

In [123]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [124]:
df.nunique()

id             99408
category           7
title          58503
body           94503
bathrooms         17
bedrooms          11
currency           1
fee                2
has_photo          3
price           3688
price_type         3
square_feet     2538
cityname        2979
state             51
latitude        7213
longitude       7271
source            25
time           75360
dtype: int64

In [125]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return (df)

In [126]:
df=encodla(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         99492 non-null  int64
 1   category                   99492 non-null  int64
 2   title                      99492 non-null  int64
 3   body                       99492 non-null  int64
 4   bathrooms                  99492 non-null  float64
 5   bedrooms                   99492 non-null  float64
 6   price                      99492 non-null  float64
 7   square_feet                99492 non-null  int64
 8   cityname                   99492 non-null  int64
 9   state                      99492 non-null  int64
 10  latitude                   99492 non-null  float64
 11  longitude                  99492 non-null  float64
 12  source                     99492 non-null  int64
 13  time                       99492 non-null  int64
 14  currency_USD               99492 non-null  int64
 15  fee_No                     99492 non-null  int64
 16  fee_Yes                    99492 non-null  int64
 17  has_photo_No               99492 non-null  int64
 18  has_photo_Thumbnail        99492 non-null  int64
 19  has_photo_Yes              99492 non-null  int64
 20  price_type_Monthly         99492 non-null  int64
 21  price_type_Monthly|Weekly  99492 non-null  int64
 22  price_type_Weekly          99492 non-null  int64
dtypes: float64(5), int64(18)
memory usage: 17.5 MB

# Train

In [127]:
x=df.drop('price',axis=1)

In [128]:
x

,id,category,title,body,bathrooms,bedrooms,square_feet,cityname,state,latitude,...,time,currency_USD,fee_No,fee_Yes,has_photo_No,has_photo_Thumbnail,has_photo_Yes,price_type_Monthly,price_type_Monthly|Weekly,price_type_Weekly
0,5668640009,1,32498,79492,1.0,1.0,542,2202,4,33.8520,...,1577360355,1,1,0,0,1,0,1,0,0
1,5668639818,1,47562,76269,1.5,3.0,1500,1834,45,37.0867,...,1577360340,1,1,0,0,1,0,1,0,0
2,5668639686,1,47833,78205,2.0,3.0,1650,2175,27,35.8230,...,1577360332,1,1,0,0,1,0,1,0,0
3,5668639659,1,51287,77143,1.0,2.0,820,2704,4,38.3622,...,1577360330,1,1,0,0,1,0,1,0,0
4,5668639374,1,32428,79349,1.0,1.0,624,21,32,35.1038,...,1577360308,1,1,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99487,5121219946,1,22300,31871,1.0,1.0,605,1196,43,29.6151,...,1544185770,1,1,0,0,0,1,1,0,0
99488,5121219696,1,45782,11473,2.0,2.0,921,1241,9,30.2254,...,1544185750,1,1,0,0,0,1,1,0,0
99489,5121219420,1,5391,15762,1.0,1.0,650,2338,4,32.7379,...,1544185729,1,1,0,0,0,1,1,0,0
99490,5121218935,1,46335,2883,1.0,1.0,701,1202,27,35.4158,...,1544185670,1,1,0,0,0,1,1,0,0
99491,5121218844,1,23453,74467,1.5,2.0,900,2338,4,32.7379,...,1544185659,1,1,0,0,0,1,1,0,0

In [129]:
y=df['price']
y

0        2195.0
1        1250.0
2        1395.0
3        1600.0
4         975.0
          ...
99487     780.0
99488     813.0
99489    1325.0
99490     931.0
99491    1595.0
Name: price, Length: 99492, dtype: float64

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [132]:
x_train.shape

(79593, 22)

In [133]:
x_test.shape

(19899, 22)

# Tree-based

In [134]:
from sklearn.tree import DecisionTreeRegressor

In [135]:
dt_reg=DecisionTreeRegressor()

In [136]:
dt_reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [137]:
y_pred=dt_reg.predict(x_test)

In [138]:
y_pred

array([1729., 2250., 1025., ..., 2505., 1085., 2700.], shape=(19899,))

# Evaluation

In [139]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [140]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [141]:
print('r2= ',r2)
print('mse=',mse)
print('rmse= ',rmse)
print('mae=',mae)

r2=  0.5399642598218988
mse= 387344.81263191026
rmse=  622.3703179232684
mae= 229.72305428822867

# Linear Regression

In [144]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [145]:
lr.fit(x_train,y_train)

LinearRegression()

In [146]:
y_pred=lr.predict(x_test)

In [147]:
y_pred

array([1118.31088606, 1402.28188694, 1634.15513141, ..., 2066.58736892,
       1163.0795159 , 1373.46892072], shape=(19899,))

In [148]:
# Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [149]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [150]:
print('r2= ',r2)
print('mse=',mse)
print('rmse= ',rmse)
print('mae=',mae)

r2=  0.2504152961512591
mse= 631141.7164058367
rmse=  794.4442814986063
mae= 486.2214255085094