# Tree-Based Algorithm

In [39]:
import pandas as pd

In [40]:
df=pd.read_csv('/Users/sunnatabdurayimov/Documents/temp_1781170705670.1228127840.csv')

In [41]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           str
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    str
 6   player_name             str
 7   competition_id          str
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), str(4)
memory usage: 169.3 MB

# Data preprocessing

In [43]:
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               6
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [44]:
df.drop('player_name',axis=1,inplace=True)

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           str
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    str
 6   competition_id          str
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int64(9), str(3)
memory usage: 156.3 MB

# Encoding

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [47]:
df.nunique()

appearance_id             1706806
game_id                     66840
player_id                   25689
player_club_id               1063
player_current_club_id        438
date                         3738
competition_id                 43
yellow_cards                    3
red_cards                       2
goals                           7
assists                         7
minutes_played                122
dtype: int64

In [51]:
def encoding(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1,inplace=True)
            else:
                df[col]=encoder.fit_transform(df[col])
    return(df)

In [52]:
df=encoding(df)
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,13,0,0,0,1,90

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int64
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int64
 6   competition_id          int64
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int64(12)
memory usage: 156.3 MB

# Scaling

In [55]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int64
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int64
 6   competition_id          int64
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int64(12)
memory usage: 156.3 MB

In [57]:
#def scaling(df):
   # num_col=df.select_dtypes(include=['int64']).columns.drop('goals')
    #df[num_col]=scaler.fit_transform(df[num_col])
    #return (df)

In [58]:
#df=scaling(df)
#df.head()

# Train

In [59]:
x=df.drop('goals',axis=1)

In [60]:
x

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,45
3,55776,2234418,73333,1274,6646,1,13,0,0,0,90
4,55777,2234421,122011,195,3008,1,13,0,0,1,90
...,...,...,...,...,...,...,...,...,...,...,...
1706801,1706086,4547798,811779,985,985,3737,12,0,0,0,83
1706802,1706087,4547798,820374,985,985,3737,12,1,0,0,7
1706803,1706088,4547798,923831,985,985,3737,12,0,0,0,90
1706804,1706089,4547798,926952,985,985,3737,12,0,0,0,90
1706805,1706090,4547798,93720,1041,1041,3737,12,0,0,0,39

In [61]:
y=df['goals']

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [64]:
x_train.shape

(1365444, 11)

In [65]:
x_test.shape

(341362, 11)

# Algorithm selection(DecisionTreeRegressor)

In [66]:
from sklearn.tree import DecisionTreeRegressor

In [68]:
dt_model=DecisionTreeRegressor()

In [70]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [71]:
y_pred=dt_model.predict(x_test)

In [72]:
y_pred

array([0., 1., 0., ..., 0., 0., 0.], shape=(341362,))

In [74]:
# evaluation
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error

In [75]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [79]:

print('r2: ',r2)
print('mse: ',mse)
print('rmse: ',rmse)
print('mae: ',mae)

r2:  -0.8698723192569389
mse:  0.207679823764801
rmse:  0.4557190184365812
mae:  0.16947990696093881

# DecisionTreeClassifier

In [80]:
from sklearn.tree import DecisionTreeClassifier

In [81]:
class_model=DecisionTreeClassifier()

In [82]:
class_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [83]:
y_pred=class_model.predict(x_test)

In [84]:
y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(341362,))

In [85]:
# evaluation
from sklearn.metrics import classification_report

In [86]:
class_report=classification_report(y_test,y_pred)

In [87]:
print(class_report)

              precision    recall  f1-score   support

           0       0.92      0.91      0.92    311810
           1       0.14      0.15      0.14     26373
           2       0.03      0.04      0.03      2820
           3       0.02      0.03      0.03       328
           4       0.00      0.00      0.00        28
           5       0.00      0.00      0.00         3

    accuracy                           0.85    341362
   macro avg       0.19      0.19      0.19    341362
weighted avg       0.85      0.85      0.85    341362

# Logistic. regression

In [88]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()

In [89]:
log_reg.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [90]:
y_pred=log_reg.predict(x_test)

In [91]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(341362,))

In [92]:
#Evaluation
from sklearn.metrics import classification_report
cl_report=classification_report(y_test,y_pred)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [93]:
print(cl_report)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95    311810
           1       0.00      0.00      0.00     26373
           2       0.00      0.00      0.00      2820
           3       0.00      0.00      0.00       328
           4       0.00      0.00      0.00        28
           5       0.00      0.00      0.00         3

    accuracy                           0.91    341362
   macro avg       0.15      0.17      0.16    341362
weighted avg       0.83      0.91      0.87    341362