# Linear Regression

In [41]:
import pandas as pd

In [42]:
df=pd.read_csv('iphonesales.csv')

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Customer_Name   100 non-null    str
 2   Country         98 non-null     str
 3   iPhone_Model    98 non-null     str
 4   Storage         98 non-null     str
 5   Color           100 non-null    str
 6   Quantity        97 non-null     float64
 7   Price           99 non-null     float64
 8   Sale_Date       100 non-null    str
 9   Payment_Method  98 non-null     str
dtypes: float64(2), int64(1), str(7)
memory usage: 7.9 KB

In [44]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,1004,Customer_4,NaN,iPhone 15 Pro Max,512GB,Black,NaN,1290.0,2025-03-24,Debit Card
4,1005,Customer_5,NaN,iPhone 15,128GB,Blue,NaN,1092.0,2025-02-01,Debit Card

In [45]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
Country           2
iPhone_Model      2
Storage           2
Color             0
Quantity          3
Price             1
Sale_Date         0
Payment_Method    2
dtype: int64

In [46]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
    return(df)

In [47]:
toldir(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Customer_Name   100 non-null    str
 2   Country         100 non-null    str
 3   iPhone_Model    100 non-null    str
 4   Storage         100 non-null    str
 5   Color           100 non-null    str
 6   Quantity        100 non-null    float64
 7   Price           100 non-null    float64
 8   Sale_Date       100 non-null    str
 9   Payment_Method  100 non-null    str
dtypes: float64(2), int64(1), str(7)
memory usage: 7.9 KB

In [48]:
df.isnull().any()

Order_ID          False
Customer_Name     False
Country           False
iPhone_Model      False
Storage           False
Color             False
Quantity          False
Price             False
Sale_Date         False
Payment_Method    False
dtype: bool

In [49]:
df.nunique()

Order_ID          100
Customer_Name     100
Country             6
iPhone_Model        6
Storage             3
Color               5
Quantity            6
Price              96
Sale_Date          65
Payment_Method      4
dtype: int64

# Encoding

In [50]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [51]:
def encodlash(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)

                df.drop(columns=[col],inplace=True)
                df[dummies.columns]=dummies
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [52]:
df=encodlash(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order_ID                    100 non-null    int64
 1   Customer_Name               100 non-null    int64
 2   Country                     100 non-null    int64
 3   iPhone_Model                100 non-null    int64
 4   Quantity                    100 non-null    float64
 5   Price                       100 non-null    float64
 6   Sale_Date                   100 non-null    int64
 7   Storage_128GB               100 non-null    int64
 8   Storage_256GB               100 non-null    int64
 9   Storage_512GB               100 non-null    int64
 10  Color_Black                 100 non-null    int64
 11  Color_Blue                  100 non-null    int64
 12  Color_Purple                100 non-null    int64
 13  Color_Red                   100 non-null    int64
 14  Color_White                 100 non-null    int64
 15  Payment_Method_Cash         100 non-null    int64
 16  Payment_Method_Credit Card  100 non-null    int64
 17  Payment_Method_Debit Card   100 non-null    int64
 18  Payment_Method_PayPal       100 non-null    int64
dtypes: float64(2), int64(17)
memory usage: 15.0 KB

In [53]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Quantity,Price,Sale_Date,Storage_128GB,Storage_256GB,Storage_512GB,Color_Black,Color_Blue,Color_Purple,Color_Red,Color_White,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_PayPal
0,1001,0,5,1,5.000000,1817.0,64,0,1,0,0,0,1,0,0,0,0,1,0
1,1002,12,0,0,1.000000,998.0,34,0,1,0,0,1,0,0,0,0,0,0,1
2,1003,23,0,5,5.000000,876.0,15,0,0,1,1,0,0,0,0,0,1,0,0
3,1004,34,4,5,3.329897,1290.0,42,0,0,1,1,0,0,0,0,0,0,1,0
4,1005,45,4,4,3.329897,1092.0,19,1,0,0,0,1,0,0,0,0,0,1,0

# Scaling

In [54]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [55]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Price')

In [56]:
num_col

Index(['Order_ID', 'Customer_Name', 'Country', 'iPhone_Model', 'Quantity',
       'Sale_Date', 'Storage_128GB', 'Storage_256GB', 'Storage_512GB',
       'Color_Black', 'Color_Blue', 'Color_Purple', 'Color_Red', 'Color_White',
       'Payment_Method_Cash', 'Payment_Method_Credit Card',
       'Payment_Method_Debit Card', 'Payment_Method_PayPal'],
      dtype='str')

In [57]:
def scaling(df):
    for col in num_col:
        df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [58]:
df=scaling(df)

In [59]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Quantity,Price,Sale_Date,Storage_128GB,Storage_256GB,Storage_512GB,Color_Black,Color_Blue,Color_Purple,Color_Red,Color_White,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_PayPal
0,0.000000,0.000000,1.0,0.2,1.000000,1817.0,1.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.010101,0.121212,0.0,0.0,0.000000,998.0,0.531250,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.020202,0.232323,0.0,1.0,1.000000,876.0,0.234375,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.030303,0.343434,0.8,1.0,0.582474,1290.0,0.656250,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.040404,0.454545,0.8,0.8,0.582474,1092.0,0.296875,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

# Train

In [60]:
from sklearn.linear_model import LinearRegression

In [61]:
lr =LinearRegression()
lr

LinearRegression()

In [62]:
x=df.drop('Price',axis=1)

In [63]:
y=df['Price']

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [66]:
lr.fit(x_train,y_train)

LinearRegression()

In [67]:
y_pred=lr.predict(x_test)

In [68]:
y_pred

array([1563.08510527, 1439.46546106, 1673.49377792, 1181.47484392,
       1620.05806029, 1470.69897374, 1564.70640522, 1716.34781926,
       1229.04748757, 1610.85127152, 1431.82546037, 1598.51339762,
       1109.04132562, 1759.05170827, 1559.51282537, 1326.446391  ,
       1346.91939019, 1602.95987015, 1441.61868699, 1280.23884212])

# Evaluation

In [69]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error

In [70]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
rmse=pow(mse,(1/2))

In [71]:
print(mse)
print(mae)
print(rmse)
print(r2)

129013.71898830582
296.55964290906206
359.1847978246098
-0.24410141388621898

#  Vazifa

In [72]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error

In [73]:
y_actual=[2,4,4.5,3,5,6,5.5,7,4,8]
y_pred=[1.5,3,4,2,5.5,6.5,6.5,8,3,9]

In [75]:
mse=mean_squared_error(y_actual,y_pred)
mae=mean_absolute_error(y_actual,y_pred)
rmse=pow(mse,(1/2))
r2=r2_score(y_actual,y_pred)

In [76]:

print(mse)
print(mae)
print(rmse)
print(r2)

0.7
0.8
0.8366600265340756
0.7619047619047619